<?php

/**
 * A set of associative arrays defining the valid option values for AMC Chapters, Committees and Activities
 *
 * @link       https://graybirch.solutions
 * @since      1.1.0
 *
 * @package    AMC_actdb_shortcode
 * @subpackage AMC_actdb_shortcode/includes
 * @author     Martin Jensen <marty@graybirch.solutions>
 */

define(
    'AMC_CHAPTERS_NAME_VALUE_TABLE',
    [
        'Berkshire' => '1',
        'Boston' => '2',
        'Connecticut' => '3',
        'DelawareValley' => '4',
        'Maine' => '5',
        'MohawkHudson' => '6',
        'Narragansett' => '7',
        'NewHampshire' => '8',
        'NY.NJ' => '9',
        'SoutheasternMA' => '10',
        'Potomac' => '11',
        'Worcester' => '12',
        'AMCStaff' => '13',
        'AMCAdventureTravel' => '14',
        'CampsCabins' => '16'
    ]
);

define(
    'AMC_CHAPTERS_VALUE_NAME_TABLE',
    [
        '1' => 'Berkshire',
        '2' => 'Boston',
        '3' => 'Connecticut',
        '4' => 'DelawareValley',
        '5' => 'Maine',
        '6' => 'MohawkHudson',
        '7' => 'Narragansett',
        '8' => 'NewHampshire',
        '9' => 'NY.NJ',
        '10' => 'SoutheasternMA',
        '11' => 'Potomac',
        '12' => 'Worcester',
        '13' => 'AMCStaff',
        '14' => 'AMCAdventureTravel',
        '16' => 'CampsCabins',
    ]
);

define(
    'AMC_COMMITTEES_VALUE_NAME_TABLE',
    [
        '02' => 'Activities',
        '04' => 'Backpacking',
        '05' => 'Bicycling',
        '06' => 'Canoeing',
        '07' => 'CanoeKayak',
        '07' => 'CanoeKayak',
        '08' => 'CapeHikes',
        '09' => 'Climbing',
        '10' => 'Communications',
        '11' => 'Conservation',
        '13' => 'EastOfTheRiver',
        '14' => 'Education',
        '15' => 'Excursions',
        '16' => 'Families',
        '17' => 'FireIsland',
        '18' => 'Paddling.Flatwater',
        '19' => 'FortyPlus',
        '20' => 'Excursions',
        '20' => 'Hiking',
        '21' => 'Hospitality',
        '24' => 'Leadership',
        '25' => 'LehighValleyGroup',
        '26' => 'LocalWalksHikes',
        '28' => 'Meetings',
        '29' => 'Membership',
        '31' => 'Mountaineering',
        '32' => 'Music',
        '33' => 'NobleView',
        '34' => 'NorthernHikes',
        '35' => 'NorthwestCamp',
        '36' => 'Paddling',
        '37' => 'Programs',
        '39' => 'Paddling.SeaKayaking',
        '42' => 'Skiing',
        '43' => 'Social',
        '44' => 'Softball',
        '46' => 'SpecialEvents',
        '47' => 'Trails',
        '48' => 'YoungMembers',
        '49' => 'Whitewater',
        '50' => 'Windsurfing',
        '52' => 'AppalachianTrail',
        '53' => 'FairfieldCounty',
        '54' => 'Outings',
        '55' => 'INTRO',
        '56' => 'ExecutiveCommittee',
        '57' => 'WalksOutings',
        '58' => 'Sailing',
        '59' => 'WalksShortHikes',
        '60' => 'HikingBackpacking',
        '61' => 'TuesdayHiking',
        '62' => 'Mohican',
        '63' => 'WildernessFirstAid',
        '64' => 'YOP',
        '66' => 'SpecialEvents',
        '67' => 'DestinationPrograms',
        '68' => 'BostonVolunteers',
        '69' => 'PinkhamVolunteers',
        '70' => 'KnubbleBayBealIsland',
        '71' => 'AMCAdventureTravel',
        '72' => 'NorthCountryVolunteers',
        '73' => 'ChapterYouthPrograms',
        '74' => 'PublicRelations',
        '75' => 'MWI',
        '77' => 'ClimbingMountaineering',
        '79' => 'Nominating',
        '81' => 'HarrimanProgram',
        '82' => 'AugustCamp',
        '83' => 'ColdRiverCamp',
        '84' => 'EchoLakeCamp',
        '85' => 'HarvardCabin',
        '86' => 'PonkapoagCamp',
        '87' => 'ThreeMileIslandCamp'
    ]
);


define(
    'AMC_ACTIVITIES_NAME_VALUE_TABLE',
    [
        'Backpacking' => '1',
        'Bicycling' => '2',
        'Bicycling.Evening' => '3',
        'Bicycling.Mountain' => '4',
        'Bicycling.Road' => '5',
        'Bicycling.Touring' => '6',
        'Birdwatching' => '74',
        'Camping' => '30',
        'ClimbingMountaineering' => '7',
        'Conservation' => '8',
        'Construction' => '42',
        'CriticalTreasure' => '41',
        'Cultural' => '66',
        'Education' => '46',
        'FirstAid' => '9',
        'FlyFishing' => '63',
        'Hiking' => '10',
        'IceSkating' => '39',
        'Instruction' => '11',
        'Leadership' => '48',
        'Leadership.Camps' => '49',
        'Leadership.Chapter' => '50',
        'Leadership.Committee' => '51',
        'LeadershipTraining' => '12',
        'Meetings' => '32',
        'Music' => '40',
        'Naturalist' => '69',
        'OfficeWork' => '52',
        'Paddling' => '13',
        'Paddling.Canoeing' => '31',
        'Paddling.Flatwater' => '14',
        'Paddling.Rafting' => '34',
        'Paddling.SeaKayaking' => '15',
        'Paddling.SUP' => '72',
        'Paddling.Whitewater' => '16',
        'Photography' => '29',
        'ProgramsPresenting' => '53',
        'RockClimbing' => '67',
        'Running' => '68',
        'Sailing' => '17',
        'Skiing' => '18',
        'Skiing.CrossCountry' => '19',
        'Skiing.Downhill' => '20',
        'Skiing.Telemark' => '21',
        'Sledding' => '22',
        'Snowshoeing' => '23',
        'SocialEvents' => '24',
        'Softball' => '25',
        'SpecialEvents' => '54',
        'SpecialtySkills' => '55',
        'Training' => '57',
        'TripLeading' => '58',
        'TripLeading.Camps' => '59',
        'TripLeading.Chapter' => '60',
        'TripLeading.MajorExcursions' => '61',
        'Walks' => '27',
        'Windsurfing' => '28',
        'Yoga' => '62'
    ]
);

define(
    'AMC_ACTIVITIES_VALUE_NAME_TABLE',
    [
        '1' => 'Backpacking',
        '2' => 'Bicycling',
        '3' => 'Bicycling.Evening',
        '4' => 'Bicycling.Mountain',
        '5' => 'Bicycling.Road',
        '6' => 'Bicycling.Touring',
        '7' => 'ClimbingMountaineering',
        '8' => 'Conservation',
        '9' => 'FirstAid',
        '10' => 'Hiking',
        '11' => 'Instruction',
        '12' => 'LeadershipTraining',
        '13' => 'Paddling',
        '14' => 'Paddling.Flatwater',
        '15' => 'Paddling.SeaKayaking',
        '16' => 'Paddling.Whitewater',
        '17' => 'Sailing',
        '18' => 'Skiing',
        '19' => 'Skiing.CrossCountry',
        '20' => 'Skiing.Downhill',
        '21' => 'Skiing.Telemark',
        '22' => 'Sledding',
        '23' => 'Snowshoeing',
        '24' => 'SocialEvents',
        '25' => 'Softball',
        '27' => 'Walks',
        '28' => 'Windsurfing',
        '29' => 'Photography',
        '30' => 'Camping',
        '31' => 'Paddling.Canoeing',
        '32' => 'Meetings',
        '34' => 'Paddling.Rafting',
        '39' => 'IceSkating',
        '40' => 'Music',
        '41' => 'CriticalTreasure',
        '42' => 'Construction',
        '46' => 'Education',
        '48' => 'Leadership',
        '49' => 'Leadership.Camps',
        '50' => 'Leadership.Chapter',
        '51' => 'Leadership.Committee',
        '52' => 'OfficeWork',
        '53' => 'ProgramsPresenting',
        '54' => 'SpecialEvents',
        '55' => 'SpecialtySkills',
        '57' => 'Training',
        '58' => 'TripLeading',
        '59' => 'TripLeading.Camps',
        '60' => 'TripLeading.Chapter',
        '61' => 'TripLeading.MajorExcursions',
        '62' => 'Yoga',
        '63' => 'FlyFishing',
        '66' => 'Cultural',
        '67' => 'RockClimbing',
        '68' => 'Running',
        '69' => 'Naturalist',
        '72' => 'Paddling.SUP',
        '74' => 'Birdwatching'
    ]
);
